config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations',
  #   # omniauth_callbacks: 'omni_auth'
  # }

  root to: 'pages#home'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :destroy]
  post 'reservations/:id/accept', to: 'reservations#accept', as: 
  :accept_reservation
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: :cancel_reservation
  post 'reservations/:id/reject', to: 'reservations#reject', as: :reject_reservation

  # get 'profiles', to: 'profiles#show', as: "profiles"
  get 'profile', to: 'profiles#my'
  get 'profile/:id', to: 'profiles#show'

  get 'home', to: 'page#home'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def my
    @user = current_user
    authorize @user
    @all_my_equipment = Equipment.where(user: @user).order(created_at: :desc)
    @my_reservations = Reservation.where(user: @user).order(created_at: :desc)
    @incoming_reservations = Reservation.where.not(user: @user).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    @their_equipment = Equipment.where(user: @user)
  end
end

app/views/profiles/my.html.erb
<div class="container-lg">
  <h1>My Profile Page</h1>
  <hr>
  <div class="container-lg">
    <div class="row">
      <div class="col col-md-4 pb-5">
        <div class="container">
          <div class="row">
            <div class="col">
              <% if @user.avatar.attached? %>
                <%= cl_image_tag @user.avatar.key, height: '160px', width: '160px', style: "object-fit: cover;", class: "rounded-circle pb-3"  %>
              <% else %>
                <div class="border-3 rounded-circle d-flex" width="40" height="40">
                  <i class="bi bi-person-bounding-box"></i>
                </div>
              <% end %>
            </div>
            <div class="col">

              <h6 class="card-subtitle mb-2 text-muted">
                <p><%= @user.email %></p>
              </h6>
              <%= link_to "Edit profile", edit_user_registration_path(@user), class: "btn btn-outline-secondary btn-sm" %>
            </div>
          </div>



        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-body">
            <h2>My Equipment</h2>
            <hr>
            <% @all_my_equipment.each do |equipment| %>
              <div class="d-flex justify-content-between">
                <div class="mb-4">
                  <p><%= equipment.name%></p>
                  <p class="text-secondary"><%= equipment.description %></p>
                </div>
                <div class="dropdown">
                  <div class="ml-4">
                    <button class="btn btn-secondary btn-sm dropdown-toggle ml-2"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Actions
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <%= link_to "View", equipment_path(equipment), class: "dropdown-item" %>
                      <%= link_to "Edit", edit_equipment_path(equipment), class: "dropdown-item" %>
                      <%= link_to "Delete", equipment_path(equipment), method: :delete, class: "dropdown-item", data: { confirm: "This will delete all the related reservations to this equipment as well. Are you sure?" } %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-body">
            <h2>My Reservations</h2>
            <hr>
            <% @my_reservations.each do |reservation| %>
              <div class="d-flex justify-content-between mb-2">
                <div>
                  <%= reservation.equipment.name %> : 
                  <%= reservation.start_date %> ~
                  <%= reservation.end_date %>
                </div>
                <div class="dropdown">
                  <div class="d-flex ml-4">
                    <div class="text-secondary"><%= reservation.status %></div>
                    <button class="btn btn-secondary btn-sm dropdown-toggle ml-2"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Actions
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <%= link_to "View", reservation_path(reservation), class: "dropdown-item" %>
                      <% if reservation.status == "Pending" %>
                        <%= link_to "Edit", edit_reservation_path(reservation), class: "dropdown-item" %>
                        <%= link_to "Cancel", cancel_reservation_path(reservation), method: :post, class: "dropdown-item" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-body">
            <h2>Incoming Requests</h2>
            <hr>
            <% @incoming_reservations.each do |reservation| %>
              <div class="d-flex justify-content-between mb-2">
                <div>
                  <%= reservation.user.email %> wants to rent 
                  <%= reservation.equipment.name %> for 
                  <%= reservation.start_date %> to <%= reservation.end_date %>
                </div>
                <div class="d-flex ml-4">
                  <p class="text-secondary"><%= reservation.status %></p>
                  <div class="dropdown">
                    <button class="btn btn-secondary btn-sm dropdown-toggle ml-2"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Actions
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <%= link_to "View", reservation_path(reservation), class: "dropdown-item" %>
                      <% if reservation.status == "Pending" %>
                        <%= link_to "Accept", accept_reservation_path(reservation), method: :post, class: "dropdown-item"%>
                        <%= link_to "Edit", edit_reservation_path(reservation), class: "dropdown-item" %>
                        <%= link_to "Reject", reject_reservation_path(reservation), method: :post, class: "dropdown-item" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<h1>Profile page</h1>

<h1>This is User <%= @user.email %>'s page</h1>