config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations',
  #   # omniauth_callbacks: 'omni_auth'
  # }

  root to: 'pages#home'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :destroy]
  post 'reservations/:id/accept', to: 'reservations#accept', as: 
  :accept_reservation
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: :cancel_reservation
  post 'reservations/:id/reject', to: 'reservations#reject', as: :reject_reservation

  # get 'profiles', to: 'profiles#show', as: "profiles"
  get 'profile', to: 'profiles#my'
  get 'profile/:id', to: 'profiles#show'

  get 'home', to: 'page#home'
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many_attached :photos
  belongs_to :user
  belongs_to :category


  include PgSearch::Model
  pg_search_scope :search_by_equipment_name,
    against: [ :name ],
    associated_against: {
      category: [ :name ]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
  validates :price_per_day, presence: true, numericality: true
  # validates :available, presence: true
  validates :location, presence: true
  validates :photos, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_equipment, only: %i[show edit update destroy]

  def index
    @equipment = policy_scope(Equipment).order(created_at: :desc)
    @markers = @equipment.geocoded.map do |equipment|
      {
        lat: equipment.latitude,
        lng: equipment.longitude
      }
    end
    if params[:query].present?
      @equipment = Equipment.search_by_equipment_name(params[:query])
    else
      @equipment
    end
  end

  def show
    authorize @equipment
    # trying to show all equipment in same category, not working
    # @related_equipment = Equipment.where(category_id: @equipment.category_id)
  end

  def new
    @equipment = Equipment.new
    authorize @equipment
  end

  def create
    @equipment = Equipment.new(equipment_params)
    authorize @equipment
    @equipment.user = current_user
    if @equipment.save
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  def edit
    authorize @equipment
  end

  def update
    authorize @equipment
    @equipment.update(equipment_params)
    if @equipment.save
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  def destroy
    authorize @equipment
    @equipment.destroy
    redirect_to profile_path(current_user)
  end

  private

  def set_equipment
    @equipment = Equipment.find(params[:id])
  end

  def equipment_params
    params.require(:equipment).permit(:name, :description, :category_id, :price_per_day, :location, photos: [])
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_equipment, only: %i[show edit update destroy]
  after_action :save_show_equipment, only: %i[create update]

  def index
    @all_equipment = Equipment.all
  end

  def show
  end

  def new
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user
  end

  def edit
  end

  def update
  end

  def destroy
    @equipment.destroy
    redirect_to
  end

  private

  def set_equipment
    @equipment = Equipment.find(params[:id])
  end

  def equipment_params
    params.require(:equipment).permit[:name, :description, :price_per_day, :image, :category_id, :available]
  end

  def save_show_equipment
    if @equipment.save
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end
end

app/views/equipment/edit.html.erb
<div class="container-lg">
  <h1>Edit Your Equipment</h1>
  <hr>
  <%= simple_form_for @equipment do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price_per_day %>
    <%#   https://github.com/heartcombo/simple_form#collections %>
    <%= f.association :category, collection: Category.order(:name), prompt: "Choose a Category" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class:"btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/equipment/index.html.erb
<div class="container text-center">
</div>
<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4">
    <%# list equipments %>
    <% @equipment.each do |equipment| %>
      <div class="p-2">
        <div class="card">
          <%# card img %>
          <div class="card-img-top">
            <% if equipment.photos.attached? %>
              <div class="p-0 border-right"
                style="width: 100%; height: 230px;
                background-image: url(
                  <%= cl_image_path(equipment.photos.first.key,
                  :transformation => {:effect => "blur:1000"}) %>);
                  background-size: cover;">
                <div class="thumbnail-backdrop" style="background-image: url(<%= cl_image_path(equipment.photos.first.key) %>);">
                </div>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-title"><%= equipment.name %></h5>
            </div>
            <p class="card-text"><%= equipment.description.truncate(130) %></p>
            <%# <a href="#" class="btn btn-primary stretched-link">Go somewhere</a> %>
            <div class="d-flex justify-content-between align-items-center">
              <%= link_to "View more", equipment_path(equipment), 
              type: "button", 
                class: 'btn btn-sm btn-outline-secondary stretched-link' 
              %>

              <small class="text-muted"><%= number_to_currency(equipment.price_per_day) %>/day</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%# A map showing the where the equipment is %>
  <div class="col-sm" id="map"
    style="width: 100%; height: 300px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/equipment/new.html.erb
<div class="container-lg">
  <h1>List Your Equipment for Rent</h1>
  <hr>
  <%# frozen_string_literal: true %>
  <%= simple_form_for @equipment do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price_per_day %>
    <%= f.input :location %>
    <%#   https://github.com/heartcombo/simple_form#collections %>
    <%= f.association :category, collection: Category.order(:name), prompt: "Choose a Category" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class:"btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/equipment/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md">


      <% if @equipment.photos.attached? %>
        <div class="p-0 border-right"
                style="width: 100%; height: 100%; min-height:260px;
                background-image: url(
                  <%= cl_image_path(@equipment.photos.first.key,
                  :transformation => {:effect => "blur:1000"}) %>);
                  background-size: cover;">
          <div class="thumbnail-backdrop" style="background-image: url(<%= cl_image_path(@equipment.photos.first.key) %>);">
          </div>
        </div>
      <% end %>

      <%# cl_image_tag @equipment.photos.key, height: 300, width: 400, crop: :fill %>
    </div>
    <div class="col-md p-5">
      <h1><%= @equipment.name %></h1>
      <h4 class="price-per-day-color">Price/day: <%= number_to_currency@equipment.price_per_day %></h4>
      <hr>
      <%= @equipment.description %>
      <hr>
      <p class="owner-color">
        <% if @equipment.user.avatar.attached? %>
          <%= cl_image_tag @equipment.user.avatar.key, height: '60px', width: '60px', style: "object-fit: cover", class: "rounded-circle"  %>
        <% else %>
          <div class="border-3 rounded-circle d-flex" width="40" height="40">
            <i class="bi bi-person-bounding-box"></i>
          </div>
        <% end %>
        Owner: <%= @equipment.user.email %>
      </p>
      <% if current_user != @equipment.user %>
      <%= link_to "Request to Rent", new_equipment_reservation_path(@equipment), class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>