config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations',
  #   # omniauth_callbacks: 'omni_auth'
  # }

  root to: 'pages#home'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :destroy]
  post 'reservations/:id/accept', to: 'reservations#accept', as: 
  :accept_reservation
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: :cancel_reservation
  post 'reservations/:id/reject', to: 'reservations#reject', as: :reject_reservation

  # get 'profiles', to: 'profiles#show', as: "profiles"
  get 'profile', to: 'profiles#my'
  get 'profile/:id', to: 'profiles#show'

  get 'home', to: 'page#home'
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to :root, class: "navbar-brand" do %>
    <%= image_tag "outdoors-icons/Cone_hop.svg" %>
    <div class="text-logo navbar-brand position-absolute top-50 start-50 translate-middle">Rentrek</div>
  <% end %>

  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <%= link_to 'List equipment for rent', new_equipment_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2' %>
        </li>

        <li class="nav-item dropdown">

          <%= tag.i class: "bi bi-person-circle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "My profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>