config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations',
  #   # omniauth_callbacks: 'omni_auth'
  # }

  root to: 'pages#home'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :destroy]
  post 'reservations/:id/accept', to: 'reservations#accept', as: 
  :accept_reservation
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: :cancel_reservation
  post 'reservations/:id/reject', to: 'reservations#reject', as: :reject_reservation

  # get 'profiles', to: 'profiles#show', as: "profiles"
  get 'profile', to: 'profiles#my'
  get 'profile/:id', to: 'profiles#show'

  get 'home', to: 'page#home'
end

app/views/pages/home.html.erb
<div class="container-fluid m-0 p-0">
  <div class="banner-image">
    <div class="banner-text">
      <div class="d-flex justify-content-center">

        <h1 class="text-logo">Rentrek</h1>
      </div>


      <p>The outrek awaits, and we can help you get ready.</p>
      <div class="form-inline">
        <div class="col-sm">
          <%= form_tag equipment_index_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control placeholder text-muted",
              placeholder: "Search for rentals"
            %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <%# <div class="row"> %>
      <%#= link_to "List Your Equipment", new_equipment_path, class: "col-lg btn btn-secondary m-2" %>
      <%#= link_to "See Listings", equipment_index_path, class: "col-lg btn btn-light m-2" %>
      <%# </div> %>
    </div>
  </div>
</div>

<div class="container pt-5">

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4">
    <%# debug @equipment %>
    <% @equipment.each do |equipment| %>
      <div class="p-2">
        <div class="card">
          <div class="card-img-top">
            <% if equipment.photos.attached? %>
              <%#= cl_image_tag equipment.photos.first.key, height: '100px', width: '100px', style: "object-fit: cover"  %>
              <div class="p-0 border-right"
                style="width: 100%; height: 230px;
                background-image: url(
                  <%= cl_image_path(equipment.photos.first.key,
                  :transformation => {:effect => "blur:1000"}) %>);
                  background-size: cover;">
                <%# raise %>
                <div class="" style="background-image: url(<%= cl_image_path(equipment.photos.first.key) %>);
                  background-size: contain; width: 100%; height: 100%; background-position: center; background-repeat: no-repeat;"></div>
                <%#= cl_image_tag equipment.photo.key, height: 'auto', width: '', style: "object-fit: contain" %>
              </div>
            <% end %>
          </div>
          <%# cl_image_tag equipment.photos.first.key, height: '200px', width: '100%', style: "object-fit: cover" %>
          <div class="card-body">
            <h5 class="card-title"><%= equipment.name %></h5>
            <p class="card-text text-muted fs-6">
              <%= equipment.description.truncate(130) %>



            </p>
            <div class="d-flex justify-content-between">
              <%= link_to "View more", equipment_path(equipment), class: 'btn btn-sm btn-outline-secondary stretched-link' %>
              <small class="text-muted"><%= number_to_currency(equipment.price_per_day) %>/day</small>
            </div>
            <%# <a href="#" class="btn btn-primary stretched-link">Go somewhere</a> %>
            <%# <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
            </div> %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%# <% @categories.each do |category| %>
  <%# <% equipment = Equipment.where(category: category) %>
  <%# <div class="card card-category bg-dark text-white"> %>
  <%# <img src="..." class="card-img" alt="..."> %>
  <%# <%= image_tag "home_page_elements/#{category.name}.jpg", class: "card-img img-category", alt: "#{category.name}" %>
  <%# <div class="card-img-overlay"> %>
  <%# </div> %>
  <%# </div> %>
  <%# <% end %>